# Generated by Django 5.1.2 on 2024-10-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesub_app', '0002_subscription_created_at_alter_subscription_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='image_spotify',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='https://avatars.mds.yandex.net/i?id=dde4bd35713a76b958690b5b494e34ce_l-9265621-images-thumbs&n=13'),
        ),
    ]
