# Generated by Django 5.1.2 on 2024-10-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesub_app', '0003_subscription_image_spotify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='image_spotify',
        ),
        migrations.AddField(
            model_name='subscription',
            name='image_background',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
