# Generated by Django 5.1.2 on 2024-10-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesub_app', '0005_guide_alter_subscription_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='podtitle',
            field=models.CharField(default='Заголовок по умолчанию', max_length=100),
        ),
    ]
