# Generated by Django 5.1.2 on 2024-10-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesub_app', '0006_guide_podtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='podtitle',
        ),
        migrations.AddField(
            model_name='guide',
            name='opisanie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='guide',
            name='prodopisanie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Продолжение подзаголовка'),
        ),
    ]
