# Generated by Django 5.1.2 on 2024-10-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinesub_app', '0007_remove_guide_podtitle_guide_opisanie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на подписку'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='opisanie',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='prodopisanie',
            field=models.CharField(max_length=100, null=True, verbose_name='Продолжение подзаголовка'),
        ),
    ]
